-- 코드를 작성해주세요
WITH FIRST_GEN AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
 SECOND_GEN AS(
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (SELECT ID FROM FIRST_GEN)
),
THIRD_GEN AS(
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (SELECT ID FROM SECOND_GEN)
)
SELECT * FROM THIRD_GEN
ORDER BY ID