WITH UNAVAILABLE AS (
  SELECT DISTINCT CAR_ID
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
  WHERE START_DATE < '2022-12-01'  -- 기간 겹침 판정
    AND END_DATE   >= '2022-11-01'
),
RATE AS (
  SELECT CAR_TYPE, (100 - DISCOUNT_RATE) * 0.01 AS DR
  FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
  WHERE DURATION_TYPE = '30일 이상'
)
SELECT
  C.CAR_ID,
  C.CAR_TYPE,
  CEILING(C.DAILY_FEE * R.DR * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN RATE R ON R.CAR_TYPE = C.CAR_TYPE
LEFT JOIN UNAVAILABLE U ON U.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE IN ('세단','SUV')
  AND U.CAR_ID IS NULL
  AND CEILING(C.DAILY_FEE * R.DR * 30) >= 500000
  AND CEILING(C.DAILY_FEE * R.DR * 30) < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
