-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME,
    CONCAT_WS(' ', U.CITY, U.STREET_ADDRESS1, U.STREET_ADDRESS2) AS 전체주소,
    CONCAT_WS('-', SUBSTRING(U.TLNO, 1, 3), 
              SUBSTRING(U.TLNO, 4, 4), 
              SUBSTRING(U.TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_USER AS U 
JOIN (
    SELECT B.WRITER_ID, COUNT(*) AS CNT
    FROM USED_GOODS_BOARD AS B
    GROUP BY B.WRITER_ID
     ) AS INFO ON INFO.WRITER_ID = U.USER_ID
WHERE INFO.CNT >= 3
ORDER BY U.USER_ID DESC