-- 코드를 작성해주세요
WITH RECURSIVE GENCTE AS (
    -- 1세대
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    -- 이후 세대
    SELECT e.ID, e.PARENT_ID, g.GEN + 1
    FROM ECOLI_DATA e
    INNER JOIN GENCTE g ON e.PARENT_ID = g.ID
),
PARENTS AS (
 SELECT DISTINCT(PARENT_ID)
 FROM ECOLI_DATA
 WHERE PARENT_ID IS NOT NULL
), 
NOCHILD AS (
    SELECT ID, PARENT_ID
    FROM ECOLI_DATA
    WHERE ID NOT IN (SELECT PARENT_ID FROM PARENTS )
)
# SELECT * FROM GENCTE
SELECT COUNT(*) AS COUNT, GEN AS GENERATION
FROM GENCTE
WHERE ID IN (SELECT ID FROM NOCHILD)
GROUP BY GEN
ORDER BY GENERATION
