-- 첫 번째 쿼리
SELECT DISTINCT CAR_ID, 
    IF (CAR_ID IN (
        SELECT CAR_ID
        FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE "20221016" BETWEEN START_DATE AND END_DATE
    ), "대여중", "대여 가능") AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC
