-- 코드를 입력하세요
WITH JT AS 
(
    SELECT FLAVOR, sum(TOTAL_ORDER) AS JTOTAL
    from JULY 
    group by FLAVOR
),
RANKED_TABLE AS (
    SELECT F.FLAVOR, (F.TOTAL_ORDER + JT.JTOTAL) AS TOTAL, RANK() OVER (ORDER BY (F.TOTAL_ORDER + JT.JTOTAL) DESC) AS R
FROM FIRST_HALF AS F
JOIN JT ON JT.FLAVOR = F.FLAVOR
ORDER BY TOTAL DESC
    )
SELECT FLAVOR
FROM RANKED_TABLE
WHERE R <= 3