-- 코드를 입력하세요
# WITH PAPP AS ( 
#     SELECT
#     A.APNT_NO, A.PT_NO, A.MCDP_CD,  A.APNT_YMD, A.MDDR_ID, D.DR_NAME
#     FROM APPOINTMENT AS A
#     WHERE A.APNT_CNCL_YN = "N" AND DATE(A.APNT_YMD) = "2022-04-13"
#     JOIN DOCTOR  D on D.DR_ID = PAPP.MDDR_ID
# )
# # SELECT PAPP.APNT_NO, PAPP.PT_NO, PAPP.MCDP_CD, D.DR_ID 
# # FROM PAPP
# SELECT * FROM PAPP

 WITH PAPP AS (
     SELECT
        A.APNT_NO, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD 
        FROM APPOINTMENT AS A
        JOIN DOCTOR  D on D.DR_ID = A.MDDR_ID
        WHERE A.APNT_CNCL_YN = "N" AND DATE(A.APNT_YMD) = "2022-04-13"
)
SELECT PAPP.APNT_NO, P.PT_NAME, PAPP.PT_NO, PAPP.MCDP_CD, PAPP.DR_NAME,  PAPP.APNT_YMD
FROM PAPP
JOIN PATIENT P ON P.PT_NO = PAPP.PT_NO
ORDER BY PAPP.APNT_YMD