-- 코드를 입력하세요
SELECT ugu.USER_ID as USER_ID, 
    ugu.NICKNAME as NICKNAME, 
    SUM(ugb.PRICE) as TOTAL_SALES
from USED_GOODS_BOARD as ugb
left join USED_GOODS_USER ugu on ugb.WRITER_ID = ugu.USER_ID
where ugb.STATUS = "DONE" 
GROUP BY USER_ID, NICKNAME
having TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC

# SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES FROM USED_GOODS_BOARD AS A
# LEFT JOIN USED_GOODS_USER AS B
# ON A.WRITER_ID  = B.USER_ID
# WHERE STATUS = 'DONE'
# GROUP BY USER_ID, NICKNAME  
# HAVING SUM(PRICE)>=700000
# ORDER BY TOTAL_SALES ASC