-- 코드를 작성해주세요
WITH GRADE_INFO AS (
SELECT EMP_NO,
    CASE 
        WHEN  AVG(SCORE) < 80 THEN 'C'
        WHEN AVG(SCORE) < 90 THEN 'B'
        WHEN AVG(SCORE) < 96 THEN 'A'
        ELSE 'S'
    END AS GRADE
FROM HR_GRADE
GROUP BY EMP_NO
)

SELECT G.EMP_NO, HRE.EMP_NAME, G.GRADE,
    CASE 
        WHEN G.GRADE ='S' THEN HRE.SAL * 0.2
        WHEN G.GRADE ='A' THEN HRE.SAL * 0.15
        WHEN G.GRADE ='B' THEN HRE.SAL * 0.1
        WHEN G.GRADE ='C' THEN HRE.SAL * 0
    END AS BONUS
FROM GRADE_INFO AS G
JOIN HR_EMPLOYEES AS HRE ON HRE.EMP_NO = G.EMP_NO
ORDER BY G.EMP_NO