
# SELECT COUNT(*) AS FISH_COUNT
# FROM FISH_INFO AS FI
# JOIN FISH_NAME_INFO AS FNI
# ON FI.FISH_TYPE = FNI.FISH_TYPE
# WHERE FI.FISH_NAME = 'BASS' OR FI.FISH_NAME = 'SNAPPER';
SELECT COUNT(*) FISH_COUNT
FROM FISH_INFO I JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE
WHERE FISH_NAME = 'BASS' OR FISH_NAME = 'SNAPPER'