-- 코드를 작성해주세요
WITH MAXINFO AS (
    select FISH_TYPE, MAX(LENGTH) AS LENGTH
        from FISH_INFO  
        GROUP BY FISH_TYPE
), 
MATCHED AS (
    SELECT FI.ID, FI.FISH_TYPE, MI.LENGTH, FI.LENGTH AS REALLENGTH
    FROM FISH_INFO AS FI
    JOIN MAXINFO AS MI ON FI.FISH_TYPE = MI.FISH_TYPE
)
SELECT MT.ID, FNI.FISH_NAME, MT.LENGTH
FROM MATCHED AS MT 
JOIN FISH_NAME_INFO AS FNI ON MT.FISH_TYPE = FNI.FISH_TYPE
WHERE MT.LENGTH = MT.REALLENGTH
ORDER BY MT.ID



