-- 코드를 작성해주세요
WITH DSAL_AVG AS (
    SELECT DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL
FROM HR_EMPLOYEES
GROUP BY DEPT_ID
)
SELECT D.DEPT_ID, H.DEPT_NAME_EN, D.AVG_SAL
FROM DSAL_AVG AS D
JOIN HR_DEPARTMENT AS H ON H.DEPT_ID = D.DEPT_ID
ORDER BY D.AVG_SAL DESC