# -- 코드를 입력하세요
WITH MAXVIEWS AS (
SELECT MAX(VIEWS) AS MAXVIEW
    FROM USED_GOODS_BOARD
),
MAX_BOARD AS (
    SELECT BOARD_ID, VIEWS
    FROM USED_GOODS_BOARD
    WHERE VIEWS = (SELECT MAXVIEW FROM MAXVIEWS)
)
SELECT CONCAT('/home/grep/src/', UGF.BOARD_ID, '/', UGF.FILE_ID, UGF.FILE_NAME,  UGF.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE UGF
JOIN MAX_BOARD MB ON MB.BOARD_ID = UGF.BOARD_ID
ORDER BY  UGF.FILE_ID DESC