-- 코드를 입력하세요
SELECT b.CATEGORY as CATEGORY, sum(bs.SALES) as TOTAL_SALES
from BOOK as b
join BOOK_SALES as bs
on b.BOOK_ID = bs.BOOK_ID
where bs.SALES_DATE LIKE '2022-01-%'
GROUP BY b.CATEGORY
order by b.CATEGORY 

# SELECT b.CATEGORY, SUM(bs.SALES) AS TOTAL_SALES
# FROM BOOK b
# JOIN BOOK_SALES bs
# ON b.BOOK_ID = bs.BOOK_ID
# WHERE bs.SALES_DATE LIKE '2022-01%'
# GROUP BY b.CATEGORY
# ORDER BY b.CATEGORY