-- 코드를 입력하세요
WITH PG AS (
    SELECT PRICE, 
    TRUNCATE(PRICE / 10000, 0) * 10000 AS PRICE_GROUP
    FROM PRODUCT
   )
 # select * from pg
 SELECT PRICE_GROUP, COUNT(PRICE) AS PRODUCTS
 FROM PG
 GROUP BY PRICE_GROUP
 ORDER BY PRICE_GROUP